[package]
name = "rsrv32"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "4.5.23"
num = "0.4.3"
num-derive = "0.4.2"
num-traits = "0.2.19"
rand = "0.8.5"
strum = "0.26.3"
strum_macros = "0.26.4"
